--- #YAML:1.0
name:                Tie-Hash-MultiValue
version:             0.06
abstract:            
license:             ~
author:              
    - Joe McMahon (mcmahon@ibiblio.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Simple:                  0.44
    Tie::Hash:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
