---
abstract: 'Automatically store multiple values under a single key'
author:
  - 'Joe McMahon (mcmahon@cpan.org)'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-Hash-MultiValue
provides:
  Tie::Hash::MultiValue:
    file: lib/Tie/Hash/MultiValue.pm
    version: '1.07'
requires:
  Test::Simple: '0.44'
  Tie::Hash: '1'
version: '1.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
